### ISSUE TITLE
ogvrPluginRegisterDataWithDeleteCallback

### ISSUE THREAD

**Issue by yboger** [OSVR/OSVR-Core#1]
In the Async plugin we have:

  ogvrPluginRegisterDataWithDeleteCallback(
        ctx, &generic_deleter<DummyAsyncDevice>, static_cast<void *>(myAsync));

immediately after creating the data. Same on sync. Shouldn't we have a way to combine the creation and the registration of the deletion?

**Comment by rpavlik** [comment]
This is essentially partially handled already, and the rest merged into https://github.com/OSVR/OSVR-Core/issues/43
