### ISSUE TITLE
Need osvrRemove##TYPE##Callback methods in InterfaceCallbackC.h

### ISSUE THREAD

**Issue by JeroMiya** [OSVR/OSVR-Core#130]
Once you register a callback using one of the osvrRegister##TYPE##Callback methods in InterfaceCallbackC.h, it seems you are unable to unregister that callback. This causes issues in OSVR-Unity and OSVR-MonoGame, where the Stop() methods (which just set the managed delegates to null) eventually result in null reference exceptions, as the managed delegate is garbage collected while the unmanaged callback sticks around. If there were unregister functions, the managed code could properly clean up.

**Comment by DuFF14** [comment]
I'm curious if this manifested itself when you switched scenes multiple times in Unity (or in Mono)? I was getting an error when switching between scenes that each had a ClientKit prefab. The error message looked like it was related to this -- NullReferenceExceptions in interface callbacks. But the problem was actually having multiple ClientKits in the same scene. https://github.com/OSVR/OSVR-Unity/issues/45

**Comment by JeroMiya** [comment]
The NullReferenceExceptions are, I suspect, coming from the same issue - a native callback calling into a managed callback that has been garbage collected. The latency and performance issues of having more than one ClientKit is likely a separate issue. I can reproduce the NullReferenceException with this code, modified from the TrackerCallback.cs example in Managed-OSVR:

```C#
            OSVR.ClientKit.ClientContext context = new OSVR.ClientKit.ClientContext("org.opengoggles.exampleclients.managed.TrackerCallback");
            Interface lefthand = context.getInterface("/me/hands/left");
            var cb = new OrientationCallback(TrackerCallbacks.myOrientationCallback);
            lefthand.registerCallback(cb, IntPtr.Zero);
            // setting cb to null causes it to be garbage collected (eventually). note how the callback is still
            // called for a few iterations after being set to null - this does not 'unsubscribe' the callback.
            cb = null;
            for (int i = 0; i < 1000000; ++i)
            {
                context.update();
            }
```

**Comment by rpavlik** [comment]
Unregistering a callback is done by freeing the interface that the callback is registered on, in OSVR-Core.

**Comment by JeroMiya** [comment]
That's what I thought initially, but freeing the interface doesn't seem to stop the callbacks. Perhaps it's not working? This snippet still results in callbacks being called for a bit, and then a NullReferenceException:

```C#
            Interface lefthand = context.getInterface("/me/hands/left");
            var orientationSignal = new OrientationSignal(lefthand);
            var cb = new OrientationCallback(TrackerCallbacks.myOrientationCallback);
            lefthand.registerCallback(cb, IntPtr.Zero);
            lefthand.Free();
            lefthand = null;
            cb = null;
```

I had to add an Interface.Free method:

```C#
            public void Free()
            {
                Interface.osvrClientFreeInterface(m_interface);
                m_interface = IntPtr.Zero;
            }
```

This is with build 0.2-10-g533610f. A little out of date admittedly.

**Comment by rpavlik** [comment]
Ah, yes, so the lifetime of the .NET managed objects is not necessarily right - wasn't sure how to do something approximating the deterministic destruction/RAII I'm used to with C++, By "freeing the interface" I meant the `osvrClientFreeInterface` call - it looks like there is thus a bug in the Managed-OSVR bindings that it's not calling that at the right time.

**Comment by JeroMiya** [comment]
Hmm, well in the snippet above I'm calling osvrClientFreeInterface explicitly with the same exception and lack of unsubscribing. Am I missing a step?

As for deterministic destruction/RAll in .NET, that's the Dispose pattern. This is the official documentation:
https://msdn.microsoft.com/en-us/library/b1yfkh5e(v=vs.110).aspx
But this guide is quite a bit more comprehensive:
http://www.codeproject.com/Articles/15360/Implementing-IDisposable-and-the-Dispose-Pattern-P

I suspect a custom subclass of SafeHandle for both OSVR_ClientContext and OSVR_ClientInterface may be warranted in our case. This would simplify the IDisposable pattern for any classes that currently use IntPtr for those unmanaged types:
https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.safehandle(v=vs.100).aspx

**Comment by JeroMiya** [comment]
Moving SafeHandle/Dispose-Pattern related discussion to this issue in Managed-OSVR:
https://github.com/OSVR/Managed-OSVR/issues/9

I'm thinking of closing this issue and opening a new one specifically about osvrClientFreeInterface not unsubscribing callbacks (at least from managed code?). Do you have a preference? I could just edit this issue instead but the history/discussion might be useful.

**Comment by rpavlik** [comment]
I'd say close out this issue, since as far as I can tell, closing an interface correctly unregisters callbacks in unmanaged code.

**Comment by JeroMiya** [comment]
Sure, closing out. Still need to investigate why the managed code is still getting callbacks after freeing the interface, but I can move that to a new issue in Managed-OSVR after some investigation.
