### ISSUE TITLE
Clean up, import updated display descriptors

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Core#132]
This is without changing the schema - should import the VRVANA descriptor, and back-port changes from others (found in the Unity plugin?)

@DuFF14 @yboger Here is a json schema for the descriptors currently in OSVR-Core master - is this the format you want me to be keeping here? https://gist.github.com/rpavlik/ae6b2d033d804be81156 (It's human-readable)

**Comment by DuFF14** [comment]
If the goal is to update the display descriptors without breaking parsing as it
is now, looks like this will work.

**Comment by rpavlik** [comment]
OK. Yes, that is the current goal. Then I will make the requested changes keeping that schema for now.

**Comment by rpavlik** [comment]
Corresponding pull request merged.
