### ISSUE TITLE
OSVR Remote clients fail with internal devices

### ISSUE THREAD

**Issue by janoc** [OSVR/OSVR-Core#139]
OSVR server advertises its local devices (e.g. a Razer Hydra) in the tree as `"com_osvr_Multiserver/RazerHydra0@localhost"`. 

This causes remote clients to attempt to connect to "localhost" - which is obviously not the place where the device is being hosted, resulting in the UDP connection from the client failing. 

@rpavlik suggested a fix by doing a search & replace of `localhost` in the received tree by the actual host string used for the connection. It cannot be done reliably on the server ahead of time because on a multihomed (e.g. wifi + ethernet) machine the client connection could arrive from any of the available interfaces. 

This is related to #127

**Comment by russell-taylor** [comment]
VRPN can be configured to listen on all interfaces.  In fact, it does this by default.  This was modified so that Windows security wouldn't complain about trying to provide network access when only exposing to localhost.

**Comment by janoc** [comment]
@russell-taylor That is actually not the issue (and is good that VRPN does that). However, you could have a client connecting over e.g. ethernet and attempting to use a device that is advertised in the tree as on the wifi interface - which may not be accessible to that client. That's why the `localhost` rewriting should be done on the client - the client knows which hostname/address it used to connect to the server.

**Comment by rpavlik** [comment]
@russell-taylor This is strictly an OSVR-specific bug, not related to VRPN.
