### ISSUE TITLE
osvr_server fails to open Razer Hydra on Linux/plugins are initialized multiple times

### ISSUE THREAD

**Issue by janoc** [OSVR/OSVR-Core#162]
The server starts but then starts flooding the console with messages:
```
vrpn_HidInterface::reconnect(): Could not open device 0004:000c:00                                                                                                                                                   
   (Did you remember to run as root?)                                                                                                                                                                                
vrpn_HidInterface::reconnect(): Could not open device 0004:000c:01                                                                                                                                                   
   (Did you remember to run as root?)                                                                                                                                                                                
vrpn_HidInterface::reconnect(): Could not open device 0004:000c:00                                                                                                                                                   
   (Did you remember to run as root?)                                                                                                                                                                                
vrpn_HidInterface::reconnect(): Could not open device 0004:000c:01 
```

It isn't a permission issue (udev rules are set up correctly), because even running as root doesn't help. The same Hydra works just fine using a plain vrpn_server from older VRPN on the same machine.

I have tracked the problem down to the following:
The code manages to actually open the device, it unhooks the kernel driver and then it fails on the following line:
OSVR-Core/vendor/vrpn/submodules/hidapi/linux/hid-libusb.c:773
the call to libusb_claim_interface() fails with result code -6 (LIBUSB_ERROR_BUSY) for me, resulting in failure and the device being rejected with the above error messages.

**Comment by janoc** [comment]
It seems that the problem stems from the fact that the OSVR plugins are initialized multiple times. 

For example, the plugin instantiation callback is called 2x on server start, for unknown reasons. In the case of Hydra on Linux the device is open already from the first try when the second initialization happens and that is when the LIBUSB_ERROR_BUSY error is reported. 

This happens in Windows as well, however there the opening of the Hydra is not exclusive and the bug above doesn't get triggered by a lucky coincidence.

**Comment by rpavlik** [comment]
So I did recently fix the plugin loading multiple times issue, and just verified that in #373 at least the initial opening (not so lucky with re-connect) of Hydras works well on Linux.  Good enough for fixed?

**Comment by janoc** [comment]
I have just updated VRPN submodule to master, pulling in your fix and that seems to have fixed the problem on my Linux. Hydra works again. 

Thanks!
