### ISSUE TITLE
(Projection) Matrix formats

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Core#188]
As some of the render code gets pulled into core, we'll need to deal with some matrix compatibility issues. The currently exposed API does basically what a fixed-function OpenGL `glFrustum` does: produces a matrix that takes column vectors (on the right) from a right handed coordinate system, to an output with "signed z" - in range `[-1, 1]`. The matrix is stored in row-major order (in a 2D C array).

Behind the scenes, I have a compile-time-parameterized version that handles most of these possibilities, essentially doing code-gen to make custom frustum generators. The configuration options to consider are, in simple to less simple order:

- Memory ordering - transpose
- Input of row vectors vs column vectors - note this and the above are basically equivalent, as a transpose is the way to change both of them.
- Left-handed vs right-handed input - negate the third column (I think? or maybe row?)
- Unsigned z range (`[0, 1]`) - hardest, varies in two elements by a factor dependent on near and far (so easiest to do while still "inside" the creation of the matrix) - see [the two implementations](https://github.com/OSVR/OSVR-Core/blob/matrix-client-api/inc/osvr/Util/ProjectionMatrix.h#L119) and [where they go in the matrix](https://github.com/OSVR/OSVR-Core/blob/matrix-client-api/inc/osvr/Util/ProjectionMatrix.h#L181)  (though note that Eigen uses row-vectors by default, so this matrix is the transpose of what actually gets spit out by the default ClientKit API...)

Possibilities of exposing this:

- Enumerating all 2^4 (or 2^3 if we can easily name the combination of memory ordering and vector layout input)
  - Pros: high performance (everybody is a direct call), high clarity of user code (each call says what kind of matrix it will receive)
  - Cons: we have to name them all somehow (cf [the 6 D3DX projection matrix functions](https://msdn.microsoft.com/en-us/library/windows/desktop/bb147302(v=vs.85).aspx) ), it's a bit more maintenance (repetitive code, etc).
- "configuring" the `DisplayConfig` object by telling it (with separate functions) what kind of matrix you want in the future to set state
  - Pros: avoids combinatorical explosion of functions, easily handles the degeneracy of the first two options, 
  - Cons: Introduces (more) state into that object, which might not be good usability-wise in the API. Implementation would either be via a function pointer, or via a switch statement through a bitfield-type thing - so you might have an indirect call or a jump table, so a little slower than the first possibility.
- A single function call with a parameter (enum or bitfield) to specify options.
  - Pros: avoids 2^4 functions, and using a bitfield would avoid 2^4 names, keeps user code clear like the first possibility.
  - Cons: Implementation likely to be through a switch (and thus probably a jump table) like one implementation of the second possibility, so not quite as fast as the first possibility.

Writing it all out like that, it seems like the first or third (probably the third) are the best options, but I wanted to get feedback.

**Comment by rpavlik** [comment]
Oh, and one more fly in the ointment, per <https://msdn.microsoft.com/en-us/library/windows/desktop/bb172912(v=vs.85).aspx>: 

> In D3DX, the _34 element of a projection matrix cannot be a negative number. If your application needs to use a negative value in this location, it should scale the entire projection matrix by -1 instead.

Oh, and D3D appears to prefer a float matrix to a double matrix - so possibilities 2 and 3 probably still mean two functions (varying by type) - not sure if it matters to keep double precision internally and cast the results back to float at the end, or if it's faster/better to do the whole calculation in float instead.

**Comment by russell-taylor** [comment]
Just so you know, the Direct3D matrix has not yet been tested and may easily be wrong.  Looking into that this morning.

**Comment by russell-taylor** [comment]
I leave the choice of the best way to implement up to you.  My approach was to produce a specific adapter for each library, but that ran aground on people wanting different flavors.  At that point, I'm tending towards just passing back the frustum parameters (near, far, left, right, top, bottom) and letting the user deal with them in whatever native way they want to.  Still trying to decide whether we should prime the fixed-function pipeline before handing back to user code, and I think that the extra work and potential for stomping their matrices means maybe we should not be (though we currently are, at least for OpenGL).

**Comment by rpavlik** [comment]
OK, ended up choosing option 3, works well enough to get a fixed-function OpenGL sample working on its own.
