### ISSUE TITLE
OSVR-Core compile fails with Boost 1.59.00

### ISSUE THREAD

**Issue by russell-taylor** [OSVR/OSVR-Core#193]
Original complaint seems to be about line 33 in convert.hpp: error C2903: 'apply' : symbol is neither a class template nor a function template (F:\taylorr\Personal\Work\consulting\Sensics\OSVR\src\OSVR-Core\src\osvr\Common\ClientInterface.cpp)

8>  ClientContext.cpp
8>  ClientInterface.cpp
8>  IPCRingBuffer.cpp
9>------ Build started: Project: header_cpp_39, Configuration: RelWithDebInfo x64 ------
10>------ Build started: Project: header_cpp_57, Configuration: RelWithDebInfo x64 ------
11>------ Build started: Project: header_cpp_59, Configuration: RelWithDebInfo x64 ------
9>  main39.cpp
10>  main57.cpp
11>  main59.cpp
8>C:\local\boost_1_59_0\boost/fusion/container/map/detail/cpp03/convert.hpp(33): error C2903: 'apply' : symbol is neither a class template nor a function template (F:\taylorr\Personal\Work\consulting\Sensics\OSVR\src\OSVR-Core\src\osvr\Common\ClientInterface.cpp)
8>          F:\taylorr\Personal\Work\consulting\Sensics\OSVR\src\OSVR-Core\inc\osvr/Common/ReportMap.h(69) : see reference to class template instantiation 'boost::fusion::result_of::as_map<boost::mpl::vector11<boost::fusion::pair<T1,T2>,boost::fusion::pair<OSVR_ButtonReport,boost::optional<osvr::common::StateMapContents<ReportType>>>,boost::fusion::pair<OSVR_PoseReport,boost::optional<osvr::common::StateMapContents<OSVR_PoseReport>>>,boost::fusion::pair<OSVR_PositionReport,boost::optional<osvr::common::StateMapContents<OSVR_PositionReport>>>,boost::fusion::pair<OSVR_OrientationReport,boost::optional<osvr::common::StateMapContents<OSVR_OrientationReport>>>,boost::fusion::pair<OSVR_ImagingReport,boost::optional<osvr::common::StateMapContents<OSVR_ImagingReport>>>,boost::fusion::pair<OSVR_Location2DReport,boost::optional<osvr::common::StateMapContents<OSVR_Location2DReport>>>,boost::fusion::pair<OSVR_DirectionReport,boost::optional<osvr::common::StateMapContents<OSVR_DirectionReport>>>,boost::fusion::pair<OSVR_EyeTracker2DReport,boost::optional<osvr::common::StateMapContents<OSVR_EyeTracker2DReport>>>,boost::fusion::pair<OSVR_EyeTracker3DReport,boost::optional<osvr::common::StateMapContents<OSVR_EyeTracker3DReport>>>,T>>' being compiled
8>          with
8>          [
8>              T1=OSVR_AnalogReport
8>  ,            T2=boost::optional<osvr::common::StateMapContents<OSVR_AnalogReport>>
8>  ,            ReportType=OSVR_ButtonReport
8>  ,            T=boost::fusion::pair<OSVR_EyeTrackerBlinkReport,boost::optional<osvr::common::StateMapContents<OSVR_EyeTrackerBlinkReport>>>
8>          ]
8>          F:\taylorr\Personal\Work\consulting\Sensics\OSVR\src\OSVR-Core\inc\osvr/Common/InterfaceState.h(62) : see reference to class template instantiation 'osvr::common::traits::GenerateReportMap<osvr::common::StateMapValueType<boost::mpl::_1>>' being compiled

**Comment by rpavlik** [comment]
oh ugh. This is clearly my least favorite part of the code - boost::fusion lets you do some awesome things, but it's a pain to debug (and it looks like the version you're using is using a C++03 codepath which implies there's an 11 codepath too...)  I have a replacement for our usages that should be simpler, perhaps even faster, (but depends on C++11) nearly done in a branch - would remove all boost::fusion usage.
