### ISSUE TITLE
»remove_cv« in namespace »boost« does not name a template type

### ISSUE THREAD

**Issue by ChristophHaag** [OSVR/OSVR-Core#202]
boost 1.58.0 on archlinux. Trying to compile latest git master
```
In file included from /usr/include/boost/variant/get.hpp:24:0,
                 from /home/chris/build/osvr-core/src/osvr-core/src/osvr/Common/NormalizeDeviceDescriptor.cpp:36:
/usr/include/boost/variant/detail/element_index.hpp:38:69: Fehler: »remove_cv« in namespace »boost« does not name a template type
             variant_element_functor<boost::mpl::_1, typename boost::remove_cv<T>::type >
                                                                     ^
```
I found this: https://groups.google.com/forum/#!topic/boost-devel-archive/EYlnhQKB-3M and added `#include <boost/type_traits/remove_cv.hpp>` before the get.hpp include. With this addition, osvr core compiles fine.

**Comment by rpavlik** [comment]
Great, thanks - I think a patch was recently merged for that, can you check the latest master?

**Comment by ChristophHaag** [comment]
Seems to work. Thanks.
