### ISSUE TITLE
Configuration-free server

### ISSUE THREAD

**Issue by godbyk** [OSVR/OSVR-Core#228]
Since the default config file for `osvr_server` is now empty, why should `osvr_server` require a configuration file be present at all?  I propose the following behavior:
1. If a configuration file is provided on the command line, use it (if it exists).
2. Failing (1), if an `osvr_server_config.json` file is available in the current working directory use it.
3. Failing (1) and (2), start the server using an empty `{ }` configuration.

**Comment by d235j** [comment]
I'd like to extend this a bit: between 1 and 2, look in a system path (such as $PREFIX/share).
https://github.com/OSVR/OSVR-Core/issues/238 should probably be resolved first.

**Comment by rpavlik** [comment]
Yes, it should presumably have a search path including a user directory, etc.  (The `osvr_server` binary itself is incredibly minimal - doesn't even have a proper command-line-parsing framework in use - has been basically a "good enough" launcher for the functionality that's added primarily in the osvrServer library, with little engineering attention paid to it.)

**Comment by Outurnate** [comment]
I'll take this one on
