### ISSUE TITLE
Default OSVR build on OS X is universal

### ISSUE THREAD

**Issue by d235j** [OSVR/OSVR-Core#237]
Due to explicit setting of CMAKE_OSX_ARCHITECTURES in vendor/vrpn/CMakeLists.txt and vendor/vrpn/quat/CMakeLists.txt, CMAKE_OSX_ARCHITECTURES is set to both i386 and x86_64 by default. Ideally, these would remain unset so that the platform could decide what to use (modern OS X only uses x86_64 unless explicitly set otherwise).

**Comment by rpavlik** [comment]
I was thinking those were a little weird/unneccessary. This is technically an issue over in https://github.com/vrpn/vrpn - I've filed https://github.com/vrpn/vrpn/issues/113 accordingly. If nobody says anything, I'll make the change and pull in the updated vrpn into OSVR.  (yep, I maintain both.)

**Comment by d235j** [comment]
This appears resolved.
