### ISSUE TITLE
Video-based tracker performance bottleneck

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Core#245]
Multiple profilers have identified this line as being a "hot line" and a major performance impact in the plugin:

https://github.com/OSVR/OSVR-Core/blob/master/plugins/videobasedtracker/HDKLedIdentifier.cpp#L125

Barring finding the rotation-invariant pattern match function I thought I knew of from undergrad, we should at least modify it so that rotate call isn't there - it's taking at least 6-10% of the server's total cpu usage.

**Comment by russell-taylor** [comment]
Okay, I think I know how to make it faster.  Should be able to make a long string that has almost two copies of the data and then use the standard substring call to see if we find it internally; someone will have optimized the heck out of that call, presumably.

**Comment by rpavlik** [comment]
Oh, right, of course - thanks for thinking of the thing I couldn't think of...

**Comment by russell-taylor** [comment]
Fixed in a pull request along with developer info.
