### ISSUE TITLE
Add standalone libOSVRClient build

### ISSUE THREAD

**Issue by d235j** [OSVR/OSVR-Core#253]
It would be nice if we could build libOSVRClient by itself — without the server components. At least on Mac OS X, this would make universal 32/64 bit building easier.

The annoyance here is that we have many large dependencies, the worst being OpenCV. I'm not sure if resolving https://github.com/OSVR/OSVR-Core/pull/210 will help with this.

**Comment by godbyk** [comment]
If you look at the cmake options, you can disable `BUILD_OSVR_SERVER` and similar options andn should be able to build the client individually.

**Comment by rpavlik** [comment]
At the moment, OpenCV is required even for client - will be resolved soon though. As kevin mentioned, though, you can adjust the CMake options to change what to build: these are the ones that are available https://github.com/OSVR/OSVR-Core/blob/master/cmake-local/osvrBuildOptions.cmake

**Comment by rpavlik** [comment]
Closing as "already fixed" :)  can just turn off options in CMake. And we have an option to build without OpenCV too now.
