### ISSUE TITLE
Suggest changing the name "osvr_reset_yaw" to "osvr_recenter"

### ISSUE THREAD

**Issue by yboger** [OSVR/OSVR-Core#275]
Always prefer to communicate what it does as opposed to how it does it

**Comment by rpavlik** [comment]
Well, given that it doesn't actually change the position (center), just the orientation, it is actually only changing yaw.  The API doesn't actually mention reset yaw - it's a big long phrase that's verbose but fairly clear about what it does vs. how it does it.
