### ISSUE TITLE
Inline call in RenderManagerConfig.h breaks app build

### ISSUE THREAD

**Issue by russell-taylor** [OSVR/OSVR-Core#300]
The call to getStringParameter() in this header breaks an app that includes it in a way that did not happen before this function became inline.  Get a linker error about not being able to find it, even when including osvr::osvrClient in the target link libraries.

Found this after doing a pull on core and trying to rebuild the app.  This is the RenderManager_xbox folder inside distortionizer on the xbox-controller branch of that project.

**Comment by JeroMiya** [comment]
Try adding ```osvrCommon``` to the target link libraries of any apps that include ```RenderManagerConfig.h```. Since this is an internal API, and a header-only implementation, any apps that include it must link with its dependencies directly as opposed to indirectly. I think the dependency list includes ```jsonCpp```, ```osvrUtil```, and ```osvrCommon```.

**Comment by russell-taylor** [comment]
That fixed it, thanks!
