### ISSUE TITLE
Investigate Boost 1.60

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Core#323]
IPC compatibility, specifically.  See http://www.boost.org/users/history/version_1_60_0.html

https://github.com/boostorg/interprocess/compare/boost-1.59.0...boost-1.60.0

related: https://github.com/OSVR/OSVR-Core/pull/320

**Comment by rpavlik** [comment]
Apparently the issue I noticed in their code is a non issue.
@d235j reviewed the rest of the commits and thinks they're OK. So, I think we can probably close this and get a pull request to bump the version limiters.

**Comment by d235j** [comment]
It looks like they document ABI breaking changes in the changelog at http://www.boost.org/doc/libs/1_60_0/doc/html/interprocess/acknowledgements_notes.html. The last few have been to features that were already broken or non-working.
