### ISSUE TITLE
Installing OSVR software issue

### ISSUE THREAD

**Issue by Nakonzaid** [OSVR/OSVR-Core#325]
Hello!
First of all, sorry for my English. It's not my first language (I'm spanish).

I'm having serious trouble with OSVR softwarte instalation (I have Windows 7 64 Ultimate).

I've downloaded the Boxstarter bundles from:
http://access.osvr.com/binary/boxstarter
I get an executable and i ran it.

Installation started in a ms-dos window.
Little bit later, my pc was restarted itself.
Then, back in Windows desk, the ms-dos window appears again and start the installation again. 
Pc restarts, new ms-dos installation window, another restart,.... over and over again.

Obviously, it's a big problem not only for installing OSVR software but also for everything else in my pc.

Please, can anyone tell me what's going on?
How can I solve this?

Regards!

**Comment by janoc** [comment]
Hello, 

Boxstarter will try to install OSVR & *all its dependencies*, including things like Boost, VRPN, Eigen and what not. So it will take a long time. It is an automation tool mean to be used when you are setting up a development machine from scratch. 

If you only want to use OSVR (not develop it) in your applications, it is enough to download one of the precompiled installers from here: 
http://access.osvr.com/binary/osvr-core

**Comment by rpavlik** [comment]
@Nakonzaid - If you're still having problems, please email `support at osvr dot com` and we can help you further there.
