### ISSUE TITLE
Needs updated HIDAPI VRPN

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Core#338]
This will presumably result in a few changes here, but for Linux (and Mac) support to work properly with much hardware, we will need to pull updated VRPN with updated HIDAPI (and/or, modify OSVR and VRPN to also be able to handle system-built HIDAPI, which would fix things on Linux I think and probably make it easier to package there).

The corresponding VRPN pull request is https://github.com/vrpn/vrpn/pull/130 - so the current workaround for a nicely-working OSVR Core on Linux is to just update the vendor/vrpn submodule to that pull request.

**Comment by rpavlik** [comment]
Note that as a temporary workaround, you can build this branch: https://github.com/OSVR/OSVR-Core/tree/non-windows-workaround being sure to run `git submodule update` - its only difference from master as I type this is the state of the VRPN and HIDAPI submodules.

To clone this branch fresh, try

```bash
git clone --recursive https://github.com/OSVR/OSVR-Core.git --branch non-windows-workaround
```

**Comment by agirault** [comment]
+1
Support for Linux and MacOSX is I believe a big asset of OSVR compared to other VR solutions.

**Comment by rpavlik** [comment]
This is fixed and workaround no longer required! You can use the master branch since #373 was merged - just make sure that if you're using an existing git clone, that you run `git submodule update --recursive` after switching branches.
