### ISSUE TITLE
Can't execute samples

### ISSUE THREAD

**Issue by 4X6FU** [OSVR/OSVR-Core#361]
Hello All,

I am a beginner that have just got his HDK1.3 and trying to learn the OSVR...
I have installed the 'render manager',  launched the 'osvr server', enabled direct mode (running 'EnableOSVRDirectMode.exe - got success)  and try to run one of the render manager examples but failed.
The last lines of the logging in the server's console are:
....
[OSVR] Could not resolve source for /me/hands/left
[OSVR] Interface initialized for /me/hands/right
[OSVR] Could not resolve source for /me/hands/right
RenderManagerNVidiaD3D11::OpenDisplay: For vendor 0xd24e could only enable direc
t mode on 0 of 1 reportedly capable displays
RenderManagerNVidiaD3D11::OpenDisplay: Could not enable direct mode for vendor
RenderManagerD3D11OpenGL::OpenDisplay: Can't open D3D11 display
Could not open display
[OSVR] Client context shut down for com.osvr.renderManager
[OSVR] OSVR_DisplayConfigObject destructor
[OSVR] Client context shut down for com.osvr.renderManager.openGLExample

Don't know what is the reason for this. The GPU is NVIDIA GeForce GTX TITAN with driver 358.91.
Your help would be much appreciated,
Thanks,
Yossi

**Comment by russell-taylor** [comment]
I'm assuming that this is version 0.6.38 of the RenderManager installer.  You've got a good version of the nVidia drivers, but I don't know that DirectMode is supported on the Titan.  You can run the DirectModeDebugging program (in a command window) to get more information about what might be going wrong.

**Comment by 4X6FU** [comment]
Hello Russell,

Many thanks for the fast reply,

It seems the problem was the NVidia driver. I installed the last one (361.91) and now I can run the examples.

Joseph
