### ISSUE TITLE
list_usbserial on Windows

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Core#365]
Got this output on Windows - COM5 is a USB serial port, that's true, but it's for my 1532:0b00 aka HDK - not sure what the other foolishness is about (well, I know there's a WMI path there, but don't know what that thing masquerading as a VID/PID is)

```
C:\Users\Ryan\Desktop\build\OSVR-Core-vc12-ninja\bin>osvr_list_usbserial.exe
013e:013e \\WINDOWS-HS7N0FC\ROOT\CIMV2:Win32_SerialPort.DeviceID="COM5"
```

Inclined to not ship this on Windows until it works.

Concerned that it might indicate some underlying bug in the USB Serial Enum code on Windows, which IIRC @mars979 originally worked on?

**Comment by godbyk** [comment]
If appears that if you hit [line 188 in USBSerialDevInfo_Windows.h](https://github.com/OSVR/OSVR-Core/blob/master/src/osvr/USBSerial/USBSerialDevInfo_Windows.h#L188), the VID and PID are not detected or set. I'm guessing this is what's happening in your situation, but will have to investigate more thoroughly to know for sure.

(The one platform I didn't test... \<grumble\>)
