### ISSUE TITLE
OSVR Server not recognizing IR Camera

### ISSUE THREAD

**Issue by Such1337Hax0r** [OSVR/OSVR-Core#378]
I'm on OS X 10.10.5, HDK 1.3
My computer sees it as 'USB Camera #2' but osvr_server when detecting hardware says '[OSVR] Added device: com_osvr_Multiserver/OSVRHackerDevKit0 [OSVR] Added device: com_osvr_Multiserver/OSVRHackerDevKitPrediction0'

**Comment by rpavlik** [comment]
See #339 - the camera-based tracking is not yet supported on non-Windows platforms.
