### ISSUE TITLE
Intellisense Crashing

### ISSUE THREAD

**Issue by jdt3969** [OSVR/OSVR-Core#411]
Intellisense crashes and fails to work on any file that includes VideoBasedTracker.h

Within VideoBasedTracker.h declaring 
`
EstimatorList m_estimators; 
`
seems to be the source of the problem.

I have reproduced the problem on both of my machines.

The code compiles and links correctly however. May be a sign that the software engineering is a little funky while the code is technically correct.

Can someone try to reproduce? I want to rule out my systems as being the cause.
Just open VideoBasedTracker.h to reproduce.

Not critical but annoying as it removes all nice IDE features while coding.

**Comment by rpavlik** [comment]
I haven't seen this, however, I typically use the VS2015 IDE (still compiling with VS2013). What version of VS are you using? What update?

**Comment by jdt3969** [comment]
I'm using VS2013 Update 5. I'll try the 2015 IDE and see if that fixes the problem.

**Comment by jdt3969** [comment]
I tried the VS2015 IDE / VS2013 Compiler setup and it worked perfectly. Thanks!
