### ISSUE TITLE
Cannot build with Visual Studio 2015 x64

### ISSUE THREAD

**Issue by nmanjofo** [OSVR/OSVR-Core#437]
I have a problem building the project under VS2015 x64 (RTM, no update), on Win7 Professional SP1 x64

- cloned OSVR-Core via GIT using --recursive
- boost_1_59_0-msvc-14.0-64.exe
- libfunctionality build 40 x64 for VS2015 from OSVR
- jsoncpp build 18 x64 from OSVR website too

(BTW the Boxstarter package is a nice trap! It downloads tons of something, but I had to spend another hour figuring out, where the packages actually are!!! DON'T DO THAT! Or make it at least configurable...)

In CMAKE, I unchecked OpenCV (I really did now want to spend another day building OpenCV), added CMAKE_PREFIX_PATH to point to install directories of json and functionality (why don't you supply a FIND module? F.e. json has one https://github.com/cinemast/libjson-rpc-cpp/blob/master/cmake/FindJsoncpp.cmake). I also had to hand type the paths to Boost libraries, I don't know why it does not handle the BOOST_DIR path...

CMAKE complains about "CMake Warning at C:/Program Files (x86)/CMake/share/cmake-3.2/Modules/InstallRequiredSystemLibraries.cmake:424 (message): system runtime library file does not exist" but it is not an error, just warning.

CMAKE actually generates a project. But the thing is, it does not build (85/462 projects fail to build). Here is a short exaplme of what's going on: http://pastebin.com/0UParQWY. During the build, a pop-up window showing "Microsoft Optimizing Compiler has stopped working"

It seems like a bug in MSVC14 or something, don't know what to do with it. The files affected are (line number):

inc\osvr/TypePack/TypeKeyedTuple.h(55)
inc\osvr/Util/ContainerWrapper.h(185)
tests\cplusplus\TypePack\Contains.cpp(32)
tests\cplusplus\TypePack\Push.cpp(34)
inc\osvr/Util/ContainerWrapper.h(185)
inc\osvr\typepack\TypeKeyed.h(207)

I tried also boost 1.57 compiled via VS2015, same result, so BOOST should not be the villain.

**Comment by nmanjofo** [comment]
I tried to build it also via VS2013 and there are no such errors present. The only error I got was:

>------ Build started: Project: QuatExpMap, Configuration: Debug x64 ------
8>QuatExpMap.obj : error LNK2001: unresolved external symbol "class testing::internal::Mutex testing::internal::g_linked_ptr_mutex" (?g_linked_ptr_mutex@internal@testing@@3VMutex@12@A)
8>D:\knihovny\OSVR-Core\build64-msvc12\bin\Debug\QuatExpMap.exe : fatal error LNK1120: 1 unresolved externals

**Comment by d235j** [comment]
@nmanjofo can you update to VS2015 Update 2? We've had issues of this sort with the RTM version.

**Comment by nmanjofo** [comment]
Well, I am kinda running out of disk space on system drive at the moment, and the update wants me to free up 9 GB, which is currently impossible, so I cannot.

**Comment by beeryt** [comment]
I am also having this issue. I followed [these steps](https://github.com/OSVR/libfunctionality/issues/18#issuecomment-223124425) to generate the project. 

The errors I'm getting are also [unresolved external symbols](http://pastebin.com/G3EX0eHa).

**Comment by godbyk** [comment]
@beeryt There is a compiler bug in versions of VS2015 earlier than update 2. Try updating to VS2015 update 2 and compiling again.

**Comment by d235j** [comment]
@nmanjofo you might be better off uninstalling VS2015 and reinstalling it using the Update 2 installer.

**Comment by beeryt** [comment]
@godbyk My VS2015 is 14.0.25123.00 Update 2.

**Comment by rpavlik** [comment]
I'm pretty sure it's documented somewhere that you need VS2015.2 if you want to use VS2015: we found a compiler bug in VS2015 whose fix didn't make it in until 2015.2.  Is there anything else we need to do in this issue to help out, or can it be closed?

(Yes, you may have noticed the progressive de-emphasis of the boxstarter packages: they're basically best for completely bare machines like we had to set up on at CES, or machines that have never done dev before. They're no longer in the current recommended Windows build environment setup instructions.)

**Comment by beeryt** [comment]
I was able to build so there is no longer an issue for me.

**Comment by rpavlik** [comment]
FWIW - I just fixed the quatexpmap thing here: https://github.com/OSVR/OSVR-Core/pull/466
