### ISSUE TITLE
Build fails on Ubuntu 16.04.1 with Jsoncpp from apt-get

### ISSUE THREAD

**Issue by russell-taylor** [OSVR/OSVR-Core#458]
Output from verbose Makefile then a few other system introspection commands below (after the part that build some libraries okay):

make[2]: Leaving directory '/home/taylorr/build/OSVR-Core'
[ 11%] Built target vrpnserver
make -f devtools/CMakeFiles/osvr_json_to_c.dir/build.make devtools/CMakeFiles/osvr_json_to_c.dir/depend
make[2]: Entering directory '/home/taylorr/build/OSVR-Core'
cd /home/taylorr/build/OSVR-Core && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/taylorr/src/OSVR-Core /home/taylorr/src/OSVR-Core/devtools /home/taylorr/build/OSVR-Core /home/taylorr/build/OSVR-Core/devtools /home/taylorr/build/OSVR-Core/devtools/CMakeFiles/osvr_json_to_c.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/taylorr/build/OSVR-Core'
make -f devtools/CMakeFiles/osvr_json_to_c.dir/build.make devtools/CMakeFiles/osvr_json_to_c.dir/build
make[2]: Entering directory '/home/taylorr/build/OSVR-Core'
make[2]: **\* No rule to make target 'jsoncpp_lib-NOTFOUND', needed by 'bin/osvr_json_to_c'.  Stop.
make[2]: Leaving directory '/home/taylorr/build/OSVR-Core'
CMakeFiles/Makefile2:1454: recipe for target 'devtools/CMakeFiles/osvr_json_to_c.dir/all' failed
make[1]: **\* [devtools/CMakeFiles/osvr_json_to_c.dir/all] Error 2
make[1]: Leaving directory '/home/taylorr/build/OSVR-Core'
Makefile:163: recipe for target 'all' failed
make: **\* [all] Error 2
taylorr@reliasolve-3:~/build/OSVR-Core$ aptitude search jsoncpp
i   libjsoncpp-dev                       - library for reading and writing JSON for C++ (
p   libjsoncpp-dev:i386                  - library for reading and writing JSON for C++ (
p   libjsoncpp-doc                       - API documentation for libjsoncpp-dev  
i A libjsoncpp1                          - library for reading and writing JSON for C++  
p   libjsoncpp1:i386                     - library for reading and writing JSON for C++  
taylorr@reliasolve-3:~/build/OSVR-Core$ cmake --version
cmake version 3.5.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
taylorr@reliasolve-3:~/build/OSVR-Core$ cat /etc/issue
Ubuntu 16.04.1 LTS \n \l

**Comment by godbyk** [comment]
If I remember correctly, the packaged libjsoncpp doesn't ship with the CMake config script (you can run `dpkg -L libjsoncpp1` [and `libjsoncpp-dev`] to see what files it ships with). Without that config file, CMake doesn't know where to find the jsoncpp library.  CMake should complain about this at configure-time (i.e., when you run `cmake`) instead of waiting until compile-time (i.e., when you run `make`). You can try working around it by manually pointing the appropriate CMake variables at the location of the library.

**Comment by russell-taylor** [comment]
The jsoncpp_DIR value is set to /usr/lib/x86_64-linux-gnu/cmake/jsoncpp but there are no other json values in the cache for the OSVR-Core project (searched for them using cmake-gui) except for VRPN_USE_LOCAL_JSONCPP.

More info: Turning off BUILD_SERVER lets the compile get further, but then it stops working when trying to build osvrUtil.  It looks like devtools/CMakeLists.txt puts JssonCpp::JsonCpp into the link libraries for osvr_json_to_c; this should be okay because it is a required package in the root CMakeLists.txt file.  Not sure why it doesn't show up in the cache as variables that I can set.

**Comment by russell-taylor** [comment]
Building jsoncpp from source with the specified flags seems to have solved the problem, so I've added a pull request to the docs saying to do that.  You can close this issue if you want, but it would be good to be able to build with the system-provided jsoncpp libraries.

**Comment by danielamancillav** [comment]
@russell-taylor how did you build `jsoncpp` ? which flags did you specified? 
This is related to this [issue](https://github.com/open-source-parsers/jsoncpp/issues/484) i opened yesterday.

**Comment by russell-taylor** [comment]
When I build non-debug, I use the apt-get install libjsoncpp-dev version.  I haven't built jsoncpp on Linux, just on Windows.
