### ISSUE TITLE
How to register OSVR Forum?

### ISSUE THREAD

**Issue by jiapei100** [OSVR/OSVR-Core#496]
I've been trying to register http://www.osvr.org/forum . However, it looks I always receive the following error message:

> The specified username is currently inactive. If you have problems activating your account, please contact a board administrator.

However, I've already tried to contact a board administrator already, but NObody replies....

Can anybody give me a hand please?

Cheers
Pei

**Comment by godbyk** [comment]
Email this to support@osvr.org along with your desired username and someone there can assist you.
