### ISSUE TITLE
Problem compiling OSVR-Core from current master on mac

### ISSUE THREAD

**Issue by russell-taylor** [OSVR/OSVR-Core#499]
There is a difference in .h and .cpp return type, which looks like it might be tied to OSVR_UTIL_EXPORT.  This was found in commit cb295fe44f5caa81094572de0976499f53e28314 after compiling libfunctionality and doing git submodule update --init on OSVR-Core

**Comment by russell-taylor** [comment]
Here is the start of the set of error messages:

/Users/taylorr/sensics/src/OSVR-Core/src/osvr/Util/Logger.cpp:153:9: error: no type named
      'StreamProxy' in 'osvr::util::log::Logger'; did you mean
      'detail::LineLogger::StreamProxy'?
        Logger::StreamProxy Logger::trace(const char *msg) {
        ^~~~~~~~~~~~~~~~~~~
        detail::LineLogger::StreamProxy
/usr/local/include/osvr/Util/LineLogger.h:92:23: note: 'detail::LineLogger::StreamProxy'
      declared here
                class StreamProxy {
                      ^
/Users/taylorr/sensics/src/OSVR-Core/src/osvr/Util/Logger.cpp:153:37: error: return type of
      out-of-line definition of 'osvr::util::log::Logger::trace' differs from that in the
      declaration
        Logger::StreamProxy Logger::trace(const char *msg) {
                ~~~~~~~~~~~         ^
/usr/local/include/osvr/Util/Logger.h:126:49: note: previous declaration is here
            OSVR_UTIL_EXPORT detail::LineLogger trace(const char *msg);
                             ~~~~~~~~~~~~~~~~~~ ^
/Users/taylorr/sensics/src/OSVR-Core/src/osvr/Util/Logger.cpp:154:20: error: no matching
      constructor for initialization of 'detail::LineLogger::StreamProxy'
            return { *this, LogLevel::trace, msg };
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/osvr/Util/LineLogger.h:94:21: note: candidate constructor not viable:
      requires single argument 'lineLogger', but 3 arguments were provided
                    StreamProxy(LineLogger &lineLogger)
                    ^
/usr/local/include/osvr/Util/LineLogger.h:107:21: note: candidate constructor not viable:
      requires single argument 'other', but 3 arguments were provided
                    StreamProxy(StreamProxy &&other)

**Comment by godbyk** [comment]
It's pulling in this old header `/usr/local/include/osvr/Util/LineLogger.h`. It no longer exists in the latest master branch.

Also, for building on OS X with the latest Boost 1.62.0, you'll need to use the boost-1.62.0 branch.

**Comment by russell-taylor** [comment]
Deleting the old header files from /usr/local and then deleting and rebuilding worked.
