### ISSUE TITLE
Create Interface for any HMD

### ISSUE THREAD

**Issue by Pawder** [OSVR/OSVR-Core#526]
Hello,
is it possible to use OSVR code for my own software to create an interface which allows to connect any HMD? Furthermore do i need the OSVR Server to be running on my Computer in order to use osvr code?
thanks in advance

**Comment by VRguy** [comment]
Yes, OSVR is designed to connect to custom HMDs. See here for an overview of the process: http://sensics.com/integrating-hmds/
