### ISSUE TITLE
Failure while linking BasicServer in osvr-core building (Ubuntu 16.04)

### ISSUE THREAD

**Issue by danielamancillav** [OSVR/OSVR-Core#533]
Hi guys, so after following instructions about how to build osvr-core in Ubuntu, i got the following error. It seems to indicate a problem with `jsoncpp`, however i followed [this recipe](https://github.com/OSVR/OSVR-Docs/blob/master/Getting-Started/Installing/Linux-Build-Instructions.md) that seems to work for almost everybody. I use some help with this, any idea?
````
Scanning dependencies of target osvr_server
[ 89%] Building CXX object apps/CMakeFiles/osvr_server.dir/osvr_server.cpp.o
[ 89%] Linking CXX executable ../bin/BasicServer
../lib/libosvrServer.so.0.6: reference to `Json::Value::operator=(Json::Value)' undefined
../lib/libosvrServer.so.0.6: reference to `Json::Value::Value(Json::Value&&)' undefined
collect2: error: ld returned 1 exit status
apps/CMakeFiles/BasicServer.dir/build.make:100: recipe for target 'bin/BasicServer' failed
make[2]: *** [bin/BasicServer] Error 1
CMakeFiles/Makefile2:2569: recipe for target 'apps/CMakeFiles/BasicServer.dir/all' failed
make[1]: *** [apps/CMakeFiles/BasicServer.dir/all] Error 2
[ 89%] Linking CXX executable ../bin/osvr_server
../lib/libosvrServer.so.0.6: reference to `Json::Value::operator=(Json::Value)' undefined
../lib/libosvrServer.so.0.6: reference to `Json::Value::Value(Json::Value&&)'  undefined
collect2: error: ld returned 1 exit status
apps/CMakeFiles/osvr_server.dir/build.make:100: recipe for target 'bin/osvr_server' failed
make[2]: *** [bin/osvr_server] Error 1
CMakeFiles/Makefile2:2609: recipe for target 'apps/CMakeFiles/osvr_server.dir/all' failed
make[1]: *** [apps/CMakeFiles/osvr_server.dir/all] Error 2
[ 89%] Linking CXX executable ../../bin/uvbi-test-imu
[ 89%] Built target uvbi-test-imu
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```
Thanks!

**Comment by godbyk** [comment]
I run into this sort of error when I'm accidentally compiling against two different versions of jsoncpp: for example, the header files in a manually compiled version and the libraries in the system-installed version (or vice versa).

**Comment by danielamancillav** [comment]
@godbyk thank you so much for replying. So, how could i get rid of the version of `jsoncpp` that makes noise?

**Comment by godbyk** [comment]
Well, in my case, I uninstalled the system-wide version since nothing else was using it. If you're building jsoncpp yourself, I recommend using the `0.y.z` branch.

You could also run `make VERBOSE=1` to see the options CMake is passing to the compiler. That can help sort out which include paths and library is being used.

**Comment by danielamancillav** [comment]
That solved my problem. The exact solution is the following:

1) Cloned `jsoncpp` source using the `0.y.z` branch.
2) Built `jsoncpp` with cmake (using flags found [here](https://github.com/OSVR/OSVR-Core/blob/master/doc/Building.md)).
3) Replaced `json` folder in path `/usr/local/include` with the one in `/usr/local/include/jsoncpp/json` 
4) Built OSVR-CORE, then `make` and finally `sudo make install`.
