### ISSUE TITLE
Does this works on Raspberry Pi ?

### ISSUE THREAD

**Issue by zhoub** [OSVR/OSVR-Core#592]
Hi

I'd like to know if anybody or developer here already tried to make HDK2 works on Raspberry Pi or any ARM board ?

Many thanks !

**Comment by rpavlik** [comment]
It does work on arm if the machine has enough graphics power. Unfortunately
the raspberry pi does not have enough power to run the resolution and frame
rate of the hdk2, though it can run the 1.x.

**Comment by zhoub** [comment]
Thank you very much ! I'd like to order one immediately !
