### ISSUE TITLE
Sample app including rendering

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Core#66]
A relatively "bare C++"/OpenGL example that includes rendering would be useful, for those who aren't using a game engine, or who are using a game engine/scenegraph without existing VR support or an integration.

Some of the Leap Motion examples use the "Cinder" framework (primarily BSD licensed - includes Boost which is of course BSL), which might be a useful path to follow to keep the boilerplate of cross-platform OpenGL setup out of the way of the actual example.

see:
- http://libcinder.org/
- https://github.com/leapmotion-examples/VRIntro/blob/master/cmake-module/FindCinder.cmake

**Comment by russell-taylor** [comment]
It was pretty quick to get the distortionizer and latency meter running using Qt.  The distortionizer does two eyes, currently hard-coded.  Extending it to parse the various config files could be straightforward.

**Comment by yboger** [comment]
I think the distortionizer already supports the config files.

**Comment by feilen** [comment]
The most commonplace crossplatform bare-bones toolkit I've seen in use everywhere is SDL, for OpenGL rendering. Something that draws a cube or two, perhaps a simple game (that ideally could render on obscenely low-spec machines) would be ideal.

**Comment by rpavlik** [comment]
We have that since the displayconfig api got merged in - SDL examples.
