### ISSUE TITLE
Mac OS X port

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Core#72]
Should be fairly straightforward, since it did build on OS X in the past. I can think of exactly one change that would break the Mac build, and it will break with a friendly compiler error telling exactly what needs to be implemented. Any other breakage is unintentional.

See also:
https://github.com/OSVR/OSVR-Unreal/issues/4

**Comment by rpavlik** [comment]
More details on this (including what would need to be done, both for OSVR-Core, and for an Oculus driver independent of their official SDK) have been posted to <http://vrguy.blogspot.com/2015/09/advancing-vr-support-for-mac.html>

Possible help with the usbserialenum (to get it past being stubbed-out like on Android) might be found in pyserial, since it works on mac, and at least on Windows, I can filter by VID/PID: 
- https://github.com/pyserial/pyserial/blob/master/serial/serialposix.py#L187
- https://github.com/pyserial/pyserial/blob/master/serial/tools/list_ports_osx.py

cc @d235j who showed some interest

**Comment by d235j** [comment]
Thanks. I have access to Rift hardware for testing and I will hopefully obtain an OSVR HDK 1.3 once it's available for order.
By the way, I did notice that the SteamVR-OSVR plugin is out of date, and doesn't even build against the latest OpenVR SDK. What are the plans with regards to this?

**Comment by rpavlik** [comment]
Oh rats, they broke API again?

Looking for community contribution, not sure if we have someone currently lined up to work on it internally but all work will be public to avoid duplication of effort..

Back to the OS X port - first pull request merged, thanks! Would be great to get travis ci going (in general, but also) for Mac OS X build testing, since our CI setup doesn't have a Mac in it.

**Comment by d235j** [comment]
It seems like they added some required API functions that we don't implement yet. One thing at a time for me, though :)

As for Mac support for Travis: that should be fairly straightforward and I can get to it soon. I'm already using Hombrew for dependencies including libfunctionality (and a goal down the road is to have a tap for OSVR).

**Comment by rpavlik** [comment]
awesome, great to hear! Probably easier to get the Mac Travis build than the Linux, then, since you have homebrew (build from source) vs. apt (please prebuild if you can).

**Comment by d235j** [comment]
Oh right, I have to upstream a fix to the jsoncpp formula first. Once that's done, Travis compile for Mac should be rather straightforward.

**Comment by godbyk** [comment]
One more fix I had to make to vrpn to build on my Mac was to add `#include <unistd.h>` to `vrpn_Thread.C` for `mktemp`. This should be a cross-platform include (no #ifdef`s necessary).

**Comment by d235j** [comment]
That's already fixed in vrpn upstream — I just had to pull in the latest git release.

**Comment by rpavlik** [comment]
Yes, that's been pulled.

**Comment by d235j** [comment]
Next steps are to test on Windows to ensure that SDL2 is still findable and that everything builds correctly, and to set up a travis config.

**Comment by rpavlik** [comment]
I think we can mark this one as fixed and close it! Thanks, @d235j !
