### ISSUE TITLE
Don't require libfunctionality if configured to only build the client

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Core#73]
Should make it easier to build against OSVR as a submodule.

cc @Armada651

**Comment by Armada651** [comment]
It's always better to skip a dependency when it's not needed, but since libfunctionality is so small you might as well submodule it. This is another argument for splitting the repositories though, since you can then decide for each module which repositories need to be submoduled.

**Comment by rpavlik** [comment]
Fixed in a recent batch of commits, ending in https://github.com/OSVR/OSVR-Core/commit/533610fc62cfc95ee54c346774ff48f0330e612f
