### ISSUE TITLE
Be able to build an OpenCV-free version of ClientKit and deps

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Core#77]
If building just the client portion (for instance, in a submodule), we should be able to exclude OpenCV support on request to reduce dependencies. Change would require:

- Change the names of corresponding libraries (add `noimaging` to the end or something) so they didn't accidentally get used in a situation where imaging support was required
- Add aliases to exported config so that a version built with imaging would supply the noimaging target but not vice versa
- Add a configuration header to clientkit with a `HAVE_IMAGING` define inspected by at least the imaging header.
- Actually ifdef the corresponding code.

cc @Armada651

**Comment by Armada651** [comment]
I'd really like to see this change soon, this issue currently blocks integration into the Dolphin Emulator. It would also be a boon to game developers that won't have to ship OpenCV DLLs that they're not even really using.

**Comment by Armada651** [comment]
Ideally we'd get rid of the OpenCV dependency in the ClientKit completely, we can put the image data in a common data type and have the developer decide what kind of image processing library to use.

**Comment by Armada651** [comment]
I see that OSVR [already provides such a common data type](https://github.com/OSVR/OSVR-Core/blob/master/inc/osvr/ClientKit/Imaging_decl.h#L63), which means that OpenCV is used for nothing more than a wrapper in the ClientKit. Wrapping the data should be the responsibility of the application and not the ClientKit.

**Comment by rpavlik** [comment]
Internally, there is basically only the bits in Common/ImagingComponent that use OpenCV - I think there's a type constant header and their buffer-freeing/allocating functions to handle appropriately-aligned buffers to enable. Shouldn't be too hard to make this optional at the build-system level and churn out libraries (with names modified to indicate no imaging support) without that code. Happy to review or help where needed.

**Comment by Armada651** [comment]
I don't really need OpenCV to be optional on the server-side, that would just complicate things. But if we can remove the dependency on the client-side as per PR #210 that would be perfect.

**Comment by rpavlik** [comment]
merged!
